export { default as Alerts } from './Alerts'
export { default as Consultations } from './Consultations'
export { default as Dashboard } from './Dashboard'
export { default as FollowUps } from './FollowUps'
export { default as HealthChecks } from './HealthChecks'
export { default as Login } from './Login'
export { default as PatientDetail } from './PatientDetail'
export { default as Patients } from './Patients'
export { default as Profile } from './Profile'
export { default as Reports } from './Reports'
export { default as Users } from './Users'

