export { authService } from './authService'
export { patientService, type BulkUploadResult } from './patientService'
export { healthCheckService } from './healthCheckService'
export { consultationService } from './consultationService'
export { followUpService } from './followUpService'
export { alertService } from './alertService'
export { dashboardService } from './dashboardService'
export { userService } from './userService'
export { default as api } from './api'
